// Berco collections — copy is truth-safe: design references (not completed projects),
// no price, no invented specs/tolerances/warranties, no supplier or Chinese-partner names.
// Confirmed catalogue facts only (quartz, E1 board, sealed edges, soft-close). Kill-list clean.
// Image arrays are populated from the anti-slop-gated catalogue-render library.

export const ORDER = ['kitchens', 'wardrobes', 'living', 'bedrooms', 'bathrooms', 'dining', 'interior-systems']

export const CATS = {
  kitchens: {
    name: 'Kitchens',
    hero: 'Kitchens, built around you.',
    lead: 'Islands, sculleries and everyday kitchens — planned around how you cook, store and gather.',
    body: 'A kitchen is decided before it is built: layout, storage zones, appliance placement and counter flow, worked out together first. We specify surfaces and hardware we can name — quartz worktops, E1 low-emission carcases, calibrated soft-close drawers — then measure the room properly, so the fit is real and not only rendered.',
    types: [
      { name: 'Island kitchens', line: 'A working core — prep, storage and a place to gather.' },
      { name: 'Sculleries & prep', line: 'A second, quieter kitchen behind the show kitchen.' },
      { name: 'Galley & everyday', line: 'Efficient runs planned tightly around how you cook.' },
    ],
    features: ['Quartz worktops', 'Deep pan & pull-out storage', 'Soft-close throughout', 'Planned around your appliances'],
    seoTitle: 'Custom Kitchen Cabinetry in the Philippines | Berco',
    seoDesc: 'Custom kitchen cabinets, islands and sculleries for Philippine homes — planned around how you cook, specified to quartz and E1 board, and measured to fit. Design references from Berco.',
    keywords: ['custom kitchen cabinets Philippines', 'kitchen island Philippines', 'kitchen cabinetry Manila', 'scullery Philippines', 'Berco kitchens'],
    images: [
      { src: 'kitchen-island-marble-walnut-philippines.jpg', alt: 'Custom kitchen with a marble-topped island and warm walnut cabinetry — Berco design reference', cap: 'Island kitchen · design reference' },
      { src: 'warm-oak-quartz-kitchen-garden-philippines.jpg', alt: 'Warm oak and cream shaker kitchen with a quartz island and an arched opening to the garden — Berco design reference', cap: 'Oak, quartz & garden', wide: true },
      { src: 'white-wood-two-tone-kitchen-philippines.jpg', alt: 'Two-tone kitchen in white and warm wood with a wood-grain backsplash shelf and glass-front upper cabinets — Berco design reference', cap: 'White & wood, two-tone' },
      { src: 'warm-neutral-island-kitchen-philippines.jpg', alt: 'Warm neutral kitchen with a quartz island, breakfast stools and wood-lined display niches — Berco design reference', cap: 'Warm & considered', wide: true },
      { src: 'fluted-wood-island-kitchen-philippines.jpg', alt: 'Kitchen with a fluted wood island, sage tall units and a glass-front display cabinet — Berco design reference', cap: 'Fluted wood island' },
      { src: 'open-plan-kitchen-dining-philippines.jpg', alt: 'Open-plan kitchen and dining with warm cabinetry and a central island — Berco design reference', cap: 'Open-plan kitchen', wide: true },
      { src: 'warm-walnut-kitchen-cabinetry-philippines.jpg', alt: 'Warm walnut and taupe kitchen cabinetry with open shelving — Berco design reference', cap: 'Walnut & taupe' },
      { src: 'green-wood-kitchen-cabinets-philippines.jpg', alt: 'Green and wood-grain kitchen cabinets with a dark island — Berco design reference', cap: 'Colour & wood' },
      { src: 'bright-modern-kitchen-philippines.jpg', alt: 'Bright modern kitchen with island seating and dining — Berco design reference', cap: 'Bright & modern' },
      { src: 'kitchen-workstation-sink-marble-island-philippines.jpg', alt: 'Multifunction workstation sink with walnut board and colander set into a marble island — Berco design reference', cap: 'The workstation sink' },
      { src: 'custom-kitchen-cabinets-philippines.jpg', alt: 'Custom kitchen cabinets with a walnut island in a Philippine home — Berco design reference', cap: 'Everyday kitchen' },
    ],
  },
  wardrobes: {
    name: 'Wardrobes',
    hero: 'Wardrobes, tailored to how you dress.',
    lead: 'Walk-in and fitted wardrobes, arranged around your clothes — not a standard grid.',
    body: 'Hanging, drawers, shelving and lighting are planned to your wardrobe, then fitted around real walls and ceiling heights. Sealed edges and calibrated soft-close hardware keep everyday use quiet and consistent for years.',
    types: [
      { name: 'Walk-in dressing rooms', line: 'A room for clothes — hanging, drawers and display.' },
      { name: 'Fitted wardrobes', line: 'Hinged or sliding, built wall-to-wall and to the ceiling.' },
      { name: 'Reach-in & wall systems', line: 'Open or closed storage where a full room isn’t needed.' },
    ],
    features: ['Interiors arranged to your clothes', 'Integrated lighting', 'Sealed, quiet-closing hardware', 'Full-height, measured to fit'],
    seoTitle: 'Walk-in & Fitted Wardrobes in the Philippines | Berco',
    seoDesc: 'Walk-in and fitted wardrobes for Philippine homes — internal storage, fronts and lighting arranged around your clothes, measured to the room. Design references from Berco.',
    keywords: ['walk-in wardrobe Philippines', 'fitted wardrobe Philippines', 'custom closet Manila', 'bedroom wardrobe Philippines', 'Berco wardrobes'],
    images: [
      { src: 'walk-in-wardrobe-fitted-storage-philippines.jpg', alt: 'Walk-in wardrobe with fitted hanging, drawers and shelving — Berco design reference', cap: 'Walk-in wardrobe · design reference' },
      { src: 'walk-in-wardrobe-island-dresser-philippines.jpg', alt: 'Walk-in wardrobe with a central dresser island, glass-front cabinets and a display feature panel — Berco design reference', cap: 'Walk-in with dresser island', wide: true },
      { src: 'walk-in-wardrobe-island-philippines.jpg', alt: 'Walk-in wardrobe with a dressing island and glass-front storage — Berco design reference', cap: 'Dressing island', wide: true },
      { src: 'dressing-room-wardrobe-philippines.jpg', alt: 'Warm dressing room with fitted wardrobe and a full-height mirror — Berco design reference', cap: 'Dressing room' },
      { src: 'greige-walk-in-wardrobe-philippines.jpg', alt: 'Greige walk-in wardrobe with open shelving and drawers — Berco design reference', cap: 'Fitted, front to back' },
      { src: 'wardrobe-fitted-storage-organiser-philippines.jpg', alt: 'Cabinet-door pull-out organiser with fitted accessory storage — Berco design reference', cap: 'Considered interiors' },
      { src: 'walk-in-wardrobe-philippines.jpg', alt: 'Walk-in wardrobe with fitted storage and a dressing island — Berco design reference', cap: 'Tailored storage' },
    ],
  },
  living: {
    name: 'Living & Media',
    hero: 'Living, composed with restraint.',
    lead: 'Media walls, display and concealed storage that keep a living space calm.',
    body: 'Everyday things stay close and clutter stays out of sight. Cabinetry is planned around your screen, cabling and the way the room is actually used — in finishes chosen to sit quietly with the rest of the home.',
    types: [
      { name: 'Media walls', line: 'Screen, devices and cabling, planned and concealed.' },
      { name: 'Display & vitrines', line: 'Glass-front and open shelving for the things worth seeing.' },
      { name: 'Concealed storage', line: 'Everyday clutter, closed away behind a calm front.' },
    ],
    features: ['Cable & device planning', 'Open and closed, mixed', 'Finishes that sit quiet', 'Floating or full-height'],
    seoTitle: 'Living Room & Media Wall Cabinetry, Philippines | Berco',
    seoDesc: 'Media walls, display and concealed living-room storage for Philippine homes — planned around your screen, cabling and how the room is used. Design references from Berco.',
    keywords: ['media wall cabinetry Philippines', 'living room storage Philippines', 'TV wall cabinet Manila', 'display cabinet Philippines', 'Berco living'],
    images: [
      { src: 'living-room-media-storage-philippines.jpg', alt: 'Living room with a media wall and integrated display storage — Berco design reference', cap: 'Media wall · design reference' },
      { src: 'walnut-living-room-display-philippines.jpg', alt: 'Warm walnut living room with a reeded-glass display cabinet, bouclé seating and timber lounge chairs — Berco design reference', cap: 'Walnut & warm wood', wide: true },
      { src: 'living-media-wall-warm-niche-philippines.jpg', alt: 'Warm living room with a full media wall, lit display niche and low storage beneath — Berco design reference', cap: 'Media wall & display niche' },
      { src: 'living-media-wall-display-cabinetry-philippines.jpg', alt: 'Living-room media wall with lit display niches and a glass-front drinks cabinet in warm brown and brass — Berco design reference', cap: 'Media wall & display' },
      { src: 'living-media-wall-marble-feature-philippines.jpg', alt: 'Living-room media wall in soft white with wood-lined niches and a marble TV feature — Berco design reference', cap: 'Marble & wood feature' },
      { src: 'open-living-dining-cabinetry-philippines.jpg', alt: 'Open living and dining space with a full media wall and display cabinetry — Berco design reference', cap: 'Open living & dining', wide: true },
      { src: 'living-room-fireplace-cabinetry-philippines.jpg', alt: 'Living room with a fireplace flanked by built-in shelving and cabinetry — Berco design reference', cap: 'Fireplace & shelving' },
      { src: 'green-living-room-cabinetry-philippines.jpg', alt: 'Living room with green display cabinetry and open shelving — Berco design reference', cap: 'Display in colour' },
      { src: 'living-room-media-cabinetry-philippines.jpg', alt: 'Living-room media wall cabinetry with concealed storage — Berco design reference', cap: 'Everyday living' },
    ],
  },
  bedrooms: {
    name: 'Bedrooms',
    hero: 'Storage at the scale of the room.',
    lead: 'Fitted bedroom storage designed to disappear into the architecture.',
    body: 'Headboard walls, bedside and full-height wardrobes, planned so storage reads as part of the room rather than furniture placed in it — measured to the wall and finished to the light.',
    types: [
      { name: 'Headboard walls', line: 'The bed wall as one considered, built-in composition.' },
      { name: 'Full-height wardrobes', line: 'Storage that reads as architecture, not furniture.' },
      { name: 'Bedside & dressing', line: 'Fitted bedside, drawers and a place to get ready.' },
    ],
    features: ['Storage as architecture', 'Soft-close throughout', 'Measured to the wall', 'Integrated lighting'],
    seoTitle: 'Fitted Bedroom Cabinetry & Storage, Philippines | Berco',
    seoDesc: 'Fitted bedroom storage for Philippine homes — headboard walls, bedside and full-height wardrobes measured to the room and finished to the light. Design references from Berco.',
    keywords: ['fitted bedroom storage Philippines', 'bedroom cabinetry Manila', 'headboard wall Philippines', 'built-in wardrobe bedroom Philippines', 'Berco bedrooms'],
    images: [
      { src: 'fitted-bedroom-storage-philippines.jpg', alt: 'Bedroom with full-height fitted storage integrated into the wall — Berco design reference', cap: 'Fitted bedroom · design reference' },
      { src: 'bedroom-fitted-wardrobe-wood-philippines.jpg', alt: 'Bedroom with a white and warm-wood fitted wardrobe wall, dressing station and marble feature — Berco design reference', cap: 'Wood & white bedroom', wide: true },
      { src: 'warm-bedroom-built-in-wardrobe-philippines.jpg', alt: 'Warm neutral bedroom with a built-in wardrobe wall and integrated bedside storage — Berco design reference', cap: 'Warm & built-in' },
      { src: 'bedroom-cabinetry-wardrobe-philippines.jpg', alt: 'Warm bedroom with open display shelving and fitted storage — Berco design reference', cap: 'Storage as architecture', wide: true },
      { src: 'warm-bedroom-storage-philippines.jpg', alt: 'Warm bedroom with fitted shelving and bedside storage — Berco design reference', cap: 'Bedside & display' },
      { src: 'bedroom-fitted-wardrobe-philippines.jpg', alt: 'Bedroom with a fitted wardrobe wall and window seat — Berco design reference', cap: 'Full-height wardrobe' },
      { src: 'bedroom-cabinetry-philippines.jpg', alt: 'Bedroom with fitted storage and warm finishes — Berco design reference', cap: 'Quiet & fitted' },
    ],
  },
  bathrooms: {
    name: 'Bathrooms',
    hero: 'Vanities, considered for moisture.',
    lead: 'Bathroom vanities and storage specified for a wet room.',
    body: 'A bathroom asks more of a cabinet: sealed edges, moisture-considered materials and hardware that holds up to daily humidity. We plan the vanity around the plumbing and how the room is used, then fit it properly.',
    types: [
      { name: 'Floating vanities', line: 'Wall-hung, to keep a small room feeling open.' },
      { name: 'Tall & mirror storage', line: 'Full-height and mirror-front units for everything else.' },
      { name: 'Niche & recessed', line: 'Built-in nooks for a clean, uncluttered wet area.' },
    ],
    features: ['Moisture-considered materials', 'Sealed edges', 'Ventilated interiors', 'Hardware that takes humidity'],
    seoTitle: 'Bathroom Vanity Cabinetry in the Philippines | Berco',
    seoDesc: 'Bathroom vanities and storage for Philippine homes — sealed edges, moisture-considered materials and lasting hardware, planned around the plumbing. Design references from Berco.',
    keywords: ['bathroom vanity Philippines', 'custom vanity cabinet Manila', 'bathroom storage Philippines', 'moisture resistant vanity Philippines', 'Berco bathrooms'],
    images: [
      { src: 'bathroom-vanity-marble-storage-philippines.jpg', alt: 'Bathroom vanity with marble surfaces and fitted storage in a wet room — Berco design reference', cap: 'Vanity · design reference' },
      { src: 'bathroom-marble-floating-vanity-philippines.jpg', alt: 'Floating bathroom vanity with a vessel basin, oval LED mirror and a lit display niche against book-matched marble — Berco design reference', cap: 'Floating vanity in marble', wide: true },
      { src: 'bathroom-marble-shower-brass-philippines.jpg', alt: 'Bathroom with a white shaker vanity, black stone top and brass tap, lit niche and a black-framed glass shower against marble — Berco design reference', cap: 'Shaker, stone & brass' },
      { src: 'bathroom-marble-vanity-tub-philippines.jpg', alt: 'Bathroom with a white vanity and mirror cabinet beside a freestanding tub against book-matched marble — Berco design reference', cap: 'Vanity & freestanding tub' },
      { src: 'bathroom-vanity-cabinetry-philippines.jpg', alt: 'Bathroom vanity with marble surfaces and moisture-considered fitted storage — Berco design reference', cap: 'Considered for moisture', wide: true },
      { src: 'bathroom-cream-vanity-shower-philippines.jpg', alt: 'Cream bathroom vanity with mirror cabinet and a glass corner shower — Berco design reference', cap: 'Vanity & shower' },
      { src: 'bathroom-marble-vanity-pendant-philippines.jpg', alt: 'Floating bathroom vanity with a marble basin and feature wall — Berco design reference', cap: 'Marble & bronze' },
    ],
  },
  dining: {
    name: 'Dining',
    hero: 'Dining, from sideboard to display.',
    lead: 'Sideboards, bar and display cabinetry for a room made for hosting.',
    body: 'Serving, storage and display, planned into the dining area so hosting is easy and everything has a place — in materials and finishes that carry from the kitchen through to the table.',
    types: [
      { name: 'Sideboards & buffets', line: 'Serving and storage along the wall of the room.' },
      { name: 'Bar & drinks', line: 'A dedicated place to pour and to host.' },
      { name: 'Display & wine', line: 'Glass-front display and considered bottle storage.' },
    ],
    features: ['Serving-height tops', 'Display lighting', 'Concealed storage', 'Carries the kitchen finish'],
    seoTitle: 'Dining Room Sideboard & Display Cabinetry, Philippines | Berco',
    seoDesc: 'Dining-room sideboards, bar and display cabinetry for Philippine homes — serving, storage and display planned for hosting. Design references from Berco.',
    keywords: ['dining room cabinetry Philippines', 'sideboard Philippines', 'bar cabinet Manila', 'display cabinet dining Philippines', 'Berco dining'],
    images: [
      { src: 'dining-room-cabinetry-tea-room-philippines.jpg', alt: 'Dining and tea room with warm fitted cabinetry and a garden view — Berco design reference', cap: 'Dining room · design reference' },
      { src: 'dining-display-cabinetry-table-philippines.jpg', alt: 'Dining area with a marble-topped table, upholstered chairs and floor-to-ceiling display and tall cabinetry — Berco design reference', cap: 'Dining & display wall' },
      { src: 'open-plan-living-dining-warm-philippines.jpg', alt: 'Warm open-plan living and dining with a media wall, an island with bar seating and a kitchen beyond — Berco design reference', cap: 'Open-plan living & dining', wide: true },
      { src: 'open-plan-dining-kitchen-warm-philippines.jpg', alt: 'Warm open-plan dining and kitchen with wood-lined display niches, a quartz breakfast bar and a garden view — Berco design reference', cap: 'Open to the kitchen', wide: true },
      { src: 'dining-sideboard-display-philippines.jpg', alt: 'Dining area with a sideboard and display cabinetry in green and wood — Berco design reference', cap: 'Sideboard & display', wide: true },
      { src: 'dining-bar-drinks-cabinet-philippines.jpg', alt: 'Dining area with a walnut bar and drinks cabinet beside a marble display — Berco design reference', cap: 'Bar & drinks' },
      { src: 'dining-wine-display-wall-philippines.jpg', alt: 'Dining room with an illuminated built-in wine-display wall — Berco design reference', cap: 'Display & wine' },
      { src: 'dining-room-cabinetry-philippines.jpg', alt: 'Dining room with display and wine-storage cabinetry — Berco design reference', cap: 'For hosting' },
    ],
  },
  'interior-systems': {
    name: 'Interior Systems',
    hero: 'What makes a kitchen actually work.',
    lead: 'The fittings inside the cabinetry — pull-outs, organisers and the workstation sink — that make everyday storage effortless.',
    body: 'Good cabinetry is decided by what goes inside it. We plan it in the same function groups our catalogue does — drawer organisation, corner and tall storage, and sinks and taps — worked out around how you actually cook and store. Soft-close and push-to-open throughout, with named premium hardware from Kesseböhmer (Germany) and Peka (Switzerland). The flagship is a multifunction workstation sink that doubles as a second prep zone. Fitted to the cabinet, not added on.',
    types: [
      { name: 'Drawer Organisation', line: 'Base pull-outs, plate and cutlery baskets, in-drawer inserts.' },
      { name: 'Corner & Tall Storage', line: 'Larder pull-outs, lift systems and rotating corner units.' },
      { name: 'Sinks & Taps', line: 'The multifunction workstation sink, faucets and fittings.' },
    ],
    features: ['Drawer organisation & pull-outs', 'Corner & tall-unit access', 'Soft-close & push-to-open', 'Kesseböhmer · Germany · Peka · Switzerland'],
    seoTitle: 'Kitchen Interior Systems & Storage Fittings, Philippines | Berco',
    seoDesc: 'Pull-out organisers, dish and cutlery storage, corner access and the workstation sink — the fittings that make Berco cabinetry work. Design references, Philippines.',
    keywords: ['kitchen storage systems Philippines', 'pull-out organiser Philippines', 'workstation sink Philippines', 'cabinet accessories Manila', 'Berco interior systems'],
    images: [
      { src: 'kitchen-workstation-sink-marble-island-philippines.jpg', alt: 'Multifunction workstation sink with a walnut board and colander set into a marble island — Berco design reference', cap: 'The workstation sink · design reference', wide: true },
      { src: 'interior-systems-dish-cutlery-pullout-philippines.jpg', alt: 'Pull-out drawers with a fitted dish rack, cutlery-tray inserts and cup and jar organisers — Berco design reference', cap: 'Dish & cutlery pull-outs' },
      { src: 'interior-systems-jar-organiser-pullout-philippines.jpg', alt: 'Pull-out storage with a tiered spice and jar organiser and a plate rack — Berco design reference', cap: 'Spice & jar organiser' },
      { src: 'interior-systems-terracotta-pullout-storage-philippines.jpg', alt: 'Warm terracotta pull-out drawers with a fitted dish rack and cup holders — Berco design reference', cap: 'Fitted, front to back' },
      { src: 'interior-systems-worktop-integration-philippines.jpg', alt: 'Worktop with an integrated workstation sink and pull-out drawers organised with dishes and utensils beside an induction hob — Berco design reference', cap: 'Worktop & beyond', wide: true },
      { src: 'interior-systems-corner-pullout-philippines.jpg', alt: 'Corner cabinet pull-out shelving that brings pots and cookware out of the dead corner — Berco design reference', cap: 'Corner solutions' },
      { src: 'interior-systems-drawer-organisation-philippines.jpg', alt: 'Base-cabinet pull-out drawers with fitted plate, cutlery and jar organisers — Berco design reference', cap: 'Drawer organisation' },
      { src: 'interior-systems-larder-tall-storage-philippines.jpg', alt: 'Tall larder pull-out with full-extension tiers of pantry storage beside a built-in oven — Berco design reference', cap: 'Larders & tall storage' },
      { src: 'interior-systems-wall-lift-system-philippines.jpg', alt: 'Wall-cabinet pull-down lift system that brings upper-shelf storage down to reach — Berco design reference', cap: 'Wall & lift systems' },
      { src: 'interior-systems-workstation-sink-range-philippines.jpg', alt: 'Single-bowl workstation sink with a pull-out faucet set into a quartz worktop against a marble backsplash — Berco design reference', cap: 'The sink range', wide: true },
    ],
    catalogue: {
      title: 'The full Interior Systems range',
      intro: 'Every fitting, organised by function — drawer organisation, larders and tall storage, wall and lift systems, corner solutions, waste and rice, worktop integration, and sinks and taps. Codes, sizes and cabinet fits included.',
      pdf: '/berco-interior-systems-catalogue.pdf',
      pdfLabel: 'Download the Interior Systems catalogue (PDF)',
      pageDir: '/img/catalogue/interior-systems',
      pages: 32,
    },
  },
}
