// Berco collections — copy is truth-safe: design references (not completed projects),
// no price, no invented specs/tolerances/warranties, no supplier or Chinese-partner names.
// Confirmed catalogue facts only (quartz, plywood carcases + aluminium kickboards, sealed edges, soft-close). Kill-list clean.
// Image arrays are populated from the anti-slop-gated catalogue-render library.

export const ORDER = ['kitchens', 'wardrobes', 'living', 'bedrooms', 'bathrooms', 'dining', 'interior-systems']

export const CATS = {
  kitchens: {
    name: 'Kitchens',
    hero: 'Kitchens, built around you.',
    lead: 'Islands, sculleries and everyday kitchens — planned around how you cook, store and gather.',
    body: 'A kitchen is decided before it is built: layout, storage zones, appliance placement and counter flow, worked out together first. We specify surfaces and hardware we can name — quartz worktops, multi-layer plywood carcases with aluminium kickboards, calibrated soft-close drawers — then measure the room properly, so the fit is real and not only rendered.',
    types: [
      { name: 'Island kitchens', line: 'A working core — prep, storage and a place to gather.' },
      { name: 'Sculleries & prep', line: 'A second, quieter kitchen behind the show kitchen.' },
      { name: 'Galley & everyday', line: 'Efficient runs planned tightly around how you cook.' },
    ],
    features: ['Quartz worktops', 'Deep pan & pull-out storage', 'Soft-close throughout', 'Planned around your appliances'],
    seoTitle: 'Custom Kitchen Cabinetry in the Philippines | Berco',
    seoDesc: 'Custom kitchen cabinets, islands and sculleries for Philippine homes — planned around how you cook, specified to quartz and plywood carcases, and measured to fit. Design references from Berco.',
    keywords: ['custom kitchen cabinets Philippines', 'kitchen island Philippines', 'kitchen cabinetry Manila', 'scullery Philippines', 'Berco kitchens'],
    images: [
      { src: 'kitchen-island-marble-walnut-philippines.jpg', alt: 'Custom kitchen with a marble-topped island and warm walnut cabinetry — Berco design reference', cap: 'Island kitchen · design reference' },
      { src: 'warm-oak-quartz-kitchen-garden-philippines.jpg', alt: 'Warm oak and cream shaker kitchen with a quartz island and an arched opening to the garden — Berco design reference', cap: 'Oak, quartz & garden', wide: true },
      { src: 'white-wood-two-tone-kitchen-philippines.jpg', alt: 'Two-tone kitchen in white and warm wood with a wood-grain backsplash shelf and glass-front upper cabinets — Berco design reference', cap: 'White & wood, two-tone' },
      { src: 'warm-neutral-island-kitchen-philippines.jpg', alt: 'Warm neutral kitchen with a quartz island, breakfast stools and wood-lined display niches — Berco design reference', cap: 'Warm & considered', wide: true },
      { src: 'fluted-wood-island-kitchen-philippines.jpg', alt: 'Kitchen with a fluted wood island, sage tall units and a glass-front display cabinet — Berco design reference', cap: 'Fluted wood island' },
      { src: 'cream-walnut-island-kitchen-philippines.jpg', alt: 'Warm cream and walnut kitchen with an island and a tall display cabinet — Berco design reference', cap: 'Cream & walnut',  wide: true },
      { src: 'dark-wood-island-kitchen-philippines.jpg', alt: 'Dark kitchen with a warm wood island, glass display cabinets and bar seating — Berco design reference', cap: 'Dark & wood island' },
      { src: 'off-white-champagne-kitchen-philippines.jpg', alt: 'Off-white and champagne kitchen with display cabinetry and a dining table — Berco design reference', cap: 'Off-white & champagne' },
      { src: 'white-wood-parallel-kitchen-philippines.jpg', alt: 'Parallel kitchen in white and warm wood with a marble backsplash — Berco design reference', cap: 'White & wood, parallel' },
      { src: 'dark-wood-glass-cabinet-kitchen-philippines.jpg', alt: 'Warm dark-wood kitchen with floor-to-ceiling glass display cabinets and an island — Berco design reference', cap: 'Dark wood & glass' },
      { src: 'greige-island-kitchen-glass-cabinet-philippines.jpg', alt: 'Warm greige kitchen with an island, bar stools and full-height glass display cabinets — Berco design reference', cap: 'Greige & glass', wide: true },
      { src: 'white-shaker-island-kitchen-philippines.jpg', alt: 'White shaker kitchen with a large island, bar seating and glass-front display cabinets — Berco design reference', cap: 'White shaker island' },
      { src: 'grey-white-kitchen-wine-display-philippines.jpg', alt: 'Grey and white kitchen with a lit wine-display wall and a stone-topped island — Berco design reference', cap: 'Grey, white & wine' },
      { src: 'charcoal-glass-walnut-kitchen-philippines.jpg', alt: 'Galley kitchen with charcoal glass-front upper cabinets and warm walnut base units — Berco design reference', cap: 'Charcoal & walnut' },
      { src: 'open-plan-kitchen-dining-philippines.jpg', alt: 'Open-plan kitchen and dining with warm cabinetry and a central island — Berco design reference', cap: 'Open-plan kitchen', wide: true },
      { src: 'warm-walnut-kitchen-cabinetry-philippines.jpg', alt: 'Warm walnut and taupe kitchen cabinetry with open shelving — Berco design reference', cap: 'Walnut & taupe' },
      { src: 'green-wood-kitchen-cabinets-philippines.jpg', alt: 'Green and wood-grain kitchen cabinets with a dark island — Berco design reference', cap: 'Colour & wood' },
      { src: 'bright-modern-kitchen-philippines.jpg', alt: 'Bright modern kitchen with island seating and dining — Berco design reference', cap: 'Bright & modern' },
      { src: 'kitchen-workstation-sink-marble-island-philippines.jpg', alt: 'Multifunction workstation sink with walnut board and colander set into a marble island — Berco design reference', cap: 'The workstation sink' },
      { src: 'custom-kitchen-cabinets-philippines.jpg', alt: 'Custom kitchen cabinets with a walnut island in a Philippine home — Berco design reference', cap: 'Everyday kitchen' },
    ],
  },
  wardrobes: {
    name: 'Wardrobes',
    hero: 'Wardrobes, tailored to how you dress.',
    lead: 'Walk-in and fitted wardrobes, arranged around your clothes — not a standard grid.',
    body: 'Hanging, drawers, shelving and lighting are planned to your wardrobe, then fitted around real walls and ceiling heights. Sealed edges and calibrated soft-close hardware keep everyday use quiet and consistent for years.',
    types: [
      { name: 'Walk-in dressing rooms', line: 'A room for clothes — hanging, drawers and display.' },
      { name: 'Fitted wardrobes', line: 'Hinged or sliding, built wall-to-wall and to the ceiling.' },
      { name: 'Reach-in & wall systems', line: 'Open or closed storage where a full room isn’t needed.' },
    ],
    features: ['Interiors arranged to your clothes', 'Integrated lighting', 'Sealed, quiet-closing hardware', 'Full-height, measured to fit'],
    seoTitle: 'Walk-in & Fitted Wardrobes in the Philippines | Berco',
    seoDesc: 'Walk-in and fitted wardrobes for Philippine homes — internal storage, fronts and lighting arranged around your clothes, measured to the room. Design references from Berco.',
    keywords: ['walk-in wardrobe Philippines', 'fitted wardrobe Philippines', 'custom closet Manila', 'bedroom wardrobe Philippines', 'Berco wardrobes'],
    images: [
      { src: 'walk-in-wardrobe-fitted-storage-philippines.jpg', alt: 'Walk-in wardrobe with fitted hanging, drawers and shelving — Berco design reference', cap: 'Walk-in wardrobe · design reference' },
      { src: 'walk-in-wardrobe-island-dresser-philippines.jpg', alt: 'Walk-in wardrobe with a central dresser island, glass-front cabinets and a display feature panel — Berco design reference', cap: 'Walk-in with dresser island', wide: true },
      { src: 'walk-in-closet-white-fitted-philippines.jpg', alt: 'White fitted walk-in closet with hanging, drawer banks and glass-front cabinets — Berco design reference', cap: 'White, fitted throughout' },
      { src: 'walk-in-wardrobe-dark-walnut-philippines.jpg', alt: 'Dramatic dark-walnut walk-in wardrobe with a glass display cabinet and a central island — Berco design reference', cap: 'Dark walnut walk-in', wide: true },
      { src: 'bedroom-wardrobe-two-tone-philippines.jpg', alt: 'Bedroom with a two-tone fitted wardrobe wall and a dressing area — Berco design reference', cap: 'Two-tone wardrobe wall' },
      { src: 'walk-in-wardrobe-island-philippines.jpg', alt: 'Walk-in wardrobe with a dressing island and glass-front storage — Berco design reference', cap: 'Dressing island', wide: true },
      { src: 'dressing-room-wardrobe-philippines.jpg', alt: 'Warm dressing room with fitted wardrobe and a full-height mirror — Berco design reference', cap: 'Dressing room' },
      { src: 'greige-walk-in-wardrobe-philippines.jpg', alt: 'Greige walk-in wardrobe with open shelving and drawers — Berco design reference', cap: 'Fitted, front to back' },
      { src: 'wardrobe-fitted-storage-organiser-philippines.jpg', alt: 'Cabinet-door pull-out organiser with fitted accessory storage — Berco design reference', cap: 'Considered interiors' },
      { src: 'walk-in-wardrobe-backlit-gold-philippines.jpg', alt: 'Walk-in wardrobe with backlit brass-framed open shelving around a central panel — Berco design reference', cap: 'Backlit & brass' },
      { src: 'walk-in-wardrobe-mirror-run-philippines.jpg', alt: 'Long greige wardrobe run with a full-height mirror and city view — Berco design reference', cap: 'Greige run', wide: true },
      { src: 'wardrobe-vanity-dressing-area-philippines.jpg', alt: 'Fitted wardrobe with an integrated vanity and dressing area under soft light — Berco design reference', cap: 'Wardrobe & vanity' },
      { src: 'walk-in-wardrobe-warm-tiled-feature-philippines.jpg', alt: 'Warm walk-in wardrobe with a tiled feature wall and backlit hanging — Berco design reference', cap: 'Warm walk-in' },
      { src: 'dressing-room-stone-feature-philippines.jpg', alt: 'Dressing room with a stone feature wall, writing desk and fitted storage — Berco design reference', cap: 'Stone dressing room' },
      { src: 'wardrobe-copper-open-shelving-philippines.jpg', alt: 'Wardrobe wall with copper-toned open shelving and fitted cabinets — Berco design reference', cap: 'Copper shelving' },
      { src: 'walk-in-wardrobe-compact-glass-philippines.jpg', alt: 'Compact walk-in wardrobe with glass-front units and dark interior inserts — Berco design reference', cap: 'Compact walk-in' },
      { src: 'dressing-room-island-display-philippines.jpg', alt: 'Warm-wood dressing room with a display island and a wall of open shelving — Berco design reference', cap: 'Dressing island', wide: true },
      { src: 'walk-in-wardrobe-philippines.jpg', alt: 'Walk-in wardrobe with fitted storage and a dressing island — Berco design reference', cap: 'Tailored storage' },
      { src: 'sliding-wardrobe-vanity-mirror-philippines.jpg', alt: 'White sliding-door wardrobe with an integrated mirror and a timber dressing table — Berco design reference', cap: 'Sliding & vanity' },
      { src: 'beige-walk-in-island-shelving-philippines.jpg', alt: 'Beige textured walk-in closet with a drawer island and open display shelving — Berco design reference', cap: 'Beige walk-in', wide: true },
    ],
  },
  living: {
    name: 'Living & Media',
    hero: 'Living, composed with restraint.',
    lead: 'Media walls, display and concealed storage that keep a living space calm.',
    body: 'Everyday things stay close and clutter stays out of sight. Cabinetry is planned around your screen, cabling and the way the room is actually used — in finishes chosen to sit quietly with the rest of the home.',
    types: [
      { name: 'Media walls', line: 'Screen, devices and cabling, planned and concealed.' },
      { name: 'Display & vitrines', line: 'Glass-front and open shelving for the things worth seeing.' },
      { name: 'Concealed storage', line: 'Everyday clutter, closed away behind a calm front.' },
    ],
    features: ['Cable & device planning', 'Open and closed, mixed', 'Finishes that sit quiet', 'Floating or full-height'],
    seoTitle: 'Living Room & Media Wall Cabinetry, Philippines | Berco',
    seoDesc: 'Media walls, display and concealed living-room storage for Philippine homes — planned around your screen, cabling and how the room is used. Design references from Berco.',
    keywords: ['media wall cabinetry Philippines', 'living room storage Philippines', 'TV wall cabinet Manila', 'display cabinet Philippines', 'Berco living'],
    images: [
      { src: 'living-room-media-storage-philippines.jpg', alt: 'Living room with a media wall and integrated display storage — Berco design reference', cap: 'Media wall · design reference' },
      { src: 'walnut-living-room-display-philippines.jpg', alt: 'Warm walnut living room with a reeded-glass display cabinet, bouclé seating and timber lounge chairs — Berco design reference', cap: 'Walnut & warm wood', wide: true },
      { src: 'living-sea-view-media-dining-philippines.jpg', alt: 'Warm open-plan living and dining with a wood media wall, lounge seating and a sea view — Berco design reference', cap: 'Sea-view living', wide: true },
      { src: 'walnut-library-study-display-philippines.jpg', alt: 'Classic walnut home study with arched reeded-glass display cabinets and a writing desk — Berco design reference', cap: 'Walnut library' },
      { src: 'warm-living-arched-niche-tv-philippines.jpg', alt: 'Warm cream living room with an arched display niche framing the media wall — Berco design reference', cap: 'Arched niche' },
      { src: 'backlit-display-study-philippines.jpg', alt: 'Home study with arched backlit display cabinets and a leather-topped writing desk — Berco design reference', cap: 'Backlit study' },
      { src: 'bright-minimal-living-leather-philippines.jpg', alt: 'Bright minimal living room with tan leather sofas and slim open display shelving — Berco design reference', cap: 'Bright & minimal' },
      { src: 'greige-display-wall-study-philippines.jpg', alt: 'Greige living room with a full-height display wall and a sculptural writing desk — Berco design reference', cap: 'Display wall', wide: true },
      { src: 'green-media-wall-living-philippines.jpg', alt: 'Living room with a deep-green media wall, inset television and open display shelving — Berco design reference', cap: 'Green media wall' },
      { src: 'media-wall-spiral-stair-living-philippines.jpg', alt: 'Minimal living room with a wood-framed media wall beside a sculptural spiral stair — Berco design reference', cap: 'Media wall & stair' },
      { src: 'warm-media-bench-living-philippines.jpg', alt: 'Warm living room with a media wall, open display shelving and built-in bench seating — Berco design reference', cap: 'Media & bench' },
      { src: 'bright-shelving-console-living-philippines.jpg', alt: 'Bright living room with an open display-shelving wall and a sculptural console — Berco design reference', cap: 'Shelving & console' },
      { src: 'living-media-wall-warm-niche-philippines.jpg', alt: 'Warm living room with a full media wall, lit display niche and low storage beneath — Berco design reference', cap: 'Media wall & display niche' },
      { src: 'living-media-wall-minimal-philippines.jpg', alt: 'Minimal living-room media wall with a floating console and integrated display — Berco design reference', cap: 'Minimal media wall', wide: true },
      { src: 'living-media-wall-display-cabinetry-philippines.jpg', alt: 'Living-room media wall with lit display niches and a glass-front drinks cabinet in warm brown and brass — Berco design reference', cap: 'Media wall & display' },
      { src: 'living-media-wall-marble-feature-philippines.jpg', alt: 'Living-room media wall in soft white with wood-lined niches and a marble TV feature — Berco design reference', cap: 'Marble & wood feature' },
      { src: 'open-living-dining-cabinetry-philippines.jpg', alt: 'Open living and dining space with a full media wall and display cabinetry — Berco design reference', cap: 'Open living & dining', wide: true },
      { src: 'living-room-fireplace-cabinetry-philippines.jpg', alt: 'Living room with a fireplace flanked by built-in shelving and cabinetry — Berco design reference', cap: 'Fireplace & shelving' },
      { src: 'green-living-room-cabinetry-philippines.jpg', alt: 'Living room with green display cabinetry and open shelving — Berco design reference', cap: 'Display in colour' },
      { src: 'living-room-media-cabinetry-philippines.jpg', alt: 'Living-room media wall cabinetry with concealed storage — Berco design reference', cap: 'Everyday living' },
    ],
  },
  bedrooms: {
    name: 'Bedrooms',
    hero: 'Storage at the scale of the room.',
    lead: 'Fitted bedroom storage designed to disappear into the architecture.',
    body: 'Headboard walls, bedside and full-height wardrobes, planned so storage reads as part of the room rather than furniture placed in it — measured to the wall and finished to the light.',
    types: [
      { name: 'Headboard walls', line: 'The bed wall as one considered, built-in composition.' },
      { name: 'Full-height wardrobes', line: 'Storage that reads as architecture, not furniture.' },
      { name: 'Bedside & dressing', line: 'Fitted bedside, drawers and a place to get ready.' },
    ],
    features: ['Storage as architecture', 'Soft-close throughout', 'Measured to the wall', 'Integrated lighting'],
    seoTitle: 'Fitted Bedroom Cabinetry & Storage, Philippines | Berco',
    seoDesc: 'Fitted bedroom storage for Philippine homes — headboard walls, bedside and full-height wardrobes measured to the room and finished to the light. Design references from Berco.',
    keywords: ['fitted bedroom storage Philippines', 'bedroom cabinetry Manila', 'headboard wall Philippines', 'built-in wardrobe bedroom Philippines', 'Berco bedrooms'],
    images: [
      { src: 'fitted-bedroom-storage-philippines.jpg', alt: 'Bedroom with full-height fitted storage integrated into the wall — Berco design reference', cap: 'Fitted bedroom · design reference' },
      { src: 'bedroom-fitted-wardrobe-wood-philippines.jpg', alt: 'Bedroom with a white and warm-wood fitted wardrobe wall, dressing station and marble feature — Berco design reference', cap: 'Wood & white bedroom', wide: true },
      { src: 'warm-bedroom-built-in-wardrobe-philippines.jpg', alt: 'Warm neutral bedroom with a built-in wardrobe wall and integrated bedside storage — Berco design reference', cap: 'Warm & built-in' },
      { src: 'bedroom-green-fitted-wardrobe-philippines.jpg', alt: 'Bedroom with a fitted wardrobe wall in soft green and warm accents — Berco design reference', cap: 'Green & fitted', wide: true },
      { src: 'bedroom-suite-fireplace-philippines.jpg', alt: 'Bedroom suite with a fitted wardrobe, dressing area and a fireplace with a view — Berco design reference', cap: 'A bedroom suite' },
      { src: 'bedroom-tufted-tailored-philippines.jpg', alt: 'Tailored bedroom with a panelled feature wall, upholstered bed and fitted bedside storage — Berco design reference', cap: 'Panelled & tailored' },
      { src: 'bedroom-cabinetry-wardrobe-philippines.jpg', alt: 'Warm bedroom with open display shelving and fitted storage — Berco design reference', cap: 'Storage as architecture', wide: true },
      { src: 'warm-bedroom-storage-philippines.jpg', alt: 'Warm bedroom with fitted shelving and bedside storage — Berco design reference', cap: 'Bedside & display' },
      { src: 'bedroom-fitted-wardrobe-philippines.jpg', alt: 'Bedroom with a fitted wardrobe wall and window seat — Berco design reference', cap: 'Full-height wardrobe' },
      { src: 'bedroom-cabinetry-philippines.jpg', alt: 'Bedroom with fitted storage and warm finishes — Berco design reference', cap: 'Quiet & fitted' },
      { src: 'warm-grey-walnut-bedroom-fluted-philippines.jpg', alt: 'Warm grey-and-walnut bedroom with a fluted headboard wall and twin nightstands — Berco design reference', cap: 'Grey & walnut' },
      { src: 'bedroom-display-niche-glass-wardrobe-philippines.jpg', alt: 'Bedroom with a lit display niche, a dresser and a glass-front built-in wardrobe — Berco design reference', cap: 'Display & glass wardrobe' },
      { src: 'walnut-white-bedroom-walk-in-philippines.jpg', alt: 'Walnut-and-white bedroom with a platform bed and a glass-fronted walk-in behind — Berco design reference', cap: 'Walnut & walk-in', wide: true },
      { src: 'modern-bedroom-wardrobe-run-philippines.jpg', alt: 'Modern bedroom with a full-height wardrobe run and a warm timber floor — Berco design reference', cap: 'Full wardrobe run' },
      { src: 'grey-bedroom-wardrobe-dressing-niche-philippines.jpg', alt: 'Grey bedroom with a fitted wardrobe run and a lit dressing niche — Berco design reference', cap: 'Grey & dressing niche' },
      { src: 'green-cream-bedroom-fitted-wardrobe-philippines.jpg', alt: 'Green-and-cream bedroom with a fitted wardrobe and open display shelving — Berco design reference', cap: 'Green & cream' },
      { src: 'warm-bedroom-suede-headboard-bench-philippines.jpg', alt: 'Warm bedroom with a suede headboard, fitted wall panelling and a gold bench — Berco design reference', cap: 'Suede & panelling', wide: true },
      { src: 'compact-warm-bedroom-desk-philippines.jpg', alt: 'Compact warm bedroom with a built-in desk and a floating nightstand — Berco design reference', cap: 'Compact & warm' },
      { src: 'bedroom-l-wardrobe-study-desk-philippines.jpg', alt: 'Bedroom with an L-shaped fitted wardrobe and an integrated study desk — Berco design reference', cap: 'Wardrobe & study' },
      { src: 'bedroom-marble-feature-wardrobe-philippines.jpg', alt: 'Bedroom with a marble feature wall, fitted wardrobe and warm walnut trim — Berco design reference', cap: 'Marble feature' },
    ],
  },
  bathrooms: {
    name: 'Bathrooms',
    hero: 'Vanities, considered for moisture.',
    lead: 'Bathroom vanities and storage specified for a wet room.',
    body: 'A bathroom asks more of a cabinet: sealed edges, moisture-considered materials and hardware that holds up to daily humidity. We plan the vanity around the plumbing and how the room is used, then fit it properly.',
    types: [
      { name: 'Floating vanities', line: 'Wall-hung, to keep a small room feeling open.' },
      { name: 'Tall & mirror storage', line: 'Full-height and mirror-front units for everything else.' },
      { name: 'Niche & recessed', line: 'Built-in nooks for a clean, uncluttered wet area.' },
    ],
    features: ['Moisture-considered materials', 'Sealed edges', 'Ventilated interiors', 'Hardware that takes humidity'],
    seoTitle: 'Bathroom Vanity Cabinetry in the Philippines | Berco',
    seoDesc: 'Bathroom vanities and storage for Philippine homes — sealed edges, moisture-considered materials and lasting hardware, planned around the plumbing. Design references from Berco.',
    keywords: ['bathroom vanity Philippines', 'custom vanity cabinet Manila', 'bathroom storage Philippines', 'moisture resistant vanity Philippines', 'Berco bathrooms'],
    images: [
      { src: 'bathroom-vanity-marble-storage-philippines.jpg', alt: 'Bathroom vanity with marble surfaces and fitted storage in a wet room — Berco design reference', cap: 'Vanity · design reference' },
      { src: 'bathroom-marble-floating-vanity-philippines.jpg', alt: 'Floating bathroom vanity with a vessel basin, oval LED mirror and a lit display niche against book-matched marble — Berco design reference', cap: 'Floating vanity in marble', wide: true },
      { src: 'bathroom-marble-shower-brass-philippines.jpg', alt: 'Bathroom with a white shaker vanity, black stone top and brass tap, lit niche and a black-framed glass shower against marble — Berco design reference', cap: 'Shaker, stone & brass' },
      { src: 'bathroom-marble-vanity-tub-philippines.jpg', alt: 'Bathroom with a white vanity and mirror cabinet beside a freestanding tub against book-matched marble — Berco design reference', cap: 'Vanity & freestanding tub' },
      { src: 'bathroom-dark-marble-vanity-philippines.jpg', alt: 'Dramatic bathroom with a wood and dark-marble vanity, round backlit mirror and a freestanding tub — Berco design reference', cap: 'Wood & dark marble', wide: true },
      { src: 'bathroom-terracotta-vanity-tub-philippines.jpg', alt: 'Warm bathroom with a terracotta floating vanity, oval mirror, wood shelving and a freestanding tub — Berco design reference', cap: 'Warm terracotta vanity' },
      { src: 'bathroom-double-vanity-marble-philippines.jpg', alt: 'Bathroom with a white double vanity, twin mirror cabinets and book-matched marble — Berco design reference', cap: 'Double vanity in marble',  wide: true },
      { src: 'bathroom-oak-shaker-vanity-philippines.jpg', alt: 'Warm oak shaker bathroom vanity with open shelving against dark marble — Berco design reference', cap: 'Oak shaker vanity' },
      { src: 'bathroom-wood-vanity-tall-cabinet-philippines.jpg', alt: 'Bathroom with a wood vanity, black stone top and a full-height storage cabinet — Berco design reference', cap: 'Wood vanity & tall storage' },
      { src: 'bathroom-grey-marble-double-vanity-philippines.jpg', alt: 'Bathroom with a wood and grey-marble double vanity and a freestanding tub — Berco design reference', cap: 'Grey marble & wood' },
      { src: 'bathroom-wood-mirror-cabinet-philippines.jpg', alt: 'Bathroom vanity in wood tones with a mirror cabinet and a garden view — Berco design reference', cap: 'Wood & mirror cabinet' },
      { src: 'bathroom-vanity-makeup-table-philippines.jpg', alt: 'Bright bathroom with a gloss vanity, integrated makeup table and glass cabinets — Berco design reference', cap: 'Vanity & makeup table' },
      { src: 'bathroom-wood-vanity-marble-tub-philippines.jpg', alt: 'Bathroom with a wood floating vanity, marble walls and a freestanding tub by the window — Berco design reference', cap: 'Wood, marble & tub', wide: true },
      { src: 'bathroom-walnut-double-vanity-philippines.jpg', alt: 'Walnut double vanity with glass-front cabinets and twin basins against marble — Berco design reference', cap: 'Walnut double vanity' },
      { src: 'bathroom-white-marble-vanity-plant-philippines.jpg', alt: 'Bright white marble bathroom with a shaker vanity, mirror and greenery — Berco design reference', cap: 'White marble & shaker' },
      { src: 'bathroom-grey-vanity-brass-philippines.jpg', alt: 'Grey wall-mounted vanity with a mirror cabinet and a brass pendant by the window — Berco design reference', cap: 'Grey & brass' },
      { src: 'bathroom-marble-vanity-tub-mirror-philippines.jpg', alt: 'Bright marble bathroom with a floating vanity, oval mirror and a freestanding tub by the window — Berco design reference', cap: 'Marble, vanity & tub' },
      { src: 'bathroom-vanity-cabinetry-philippines.jpg', alt: 'Bathroom vanity with marble surfaces and moisture-considered fitted storage — Berco design reference', cap: 'Considered for moisture', wide: true },
      { src: 'bathroom-cream-vanity-shower-philippines.jpg', alt: 'Cream bathroom vanity with mirror cabinet and a glass corner shower — Berco design reference', cap: 'Vanity & shower' },
      { src: 'bathroom-marble-vanity-pendant-philippines.jpg', alt: 'Floating bathroom vanity with a marble basin and feature wall — Berco design reference', cap: 'Marble & bronze' },
    ],
  },
  dining: {
    name: 'Dining',
    hero: 'Dining, from sideboard to display.',
    lead: 'Sideboards, bar and display cabinetry for a room made for hosting.',
    body: 'Serving, storage and display, planned into the dining area so hosting is easy and everything has a place — in materials and finishes that carry from the kitchen through to the table.',
    types: [
      { name: 'Sideboards & buffets', line: 'Serving and storage along the wall of the room.' },
      { name: 'Bar & drinks', line: 'A dedicated place to pour and to host.' },
      { name: 'Display & wine', line: 'Glass-front display and considered bottle storage.' },
    ],
    features: ['Serving-height tops', 'Display lighting', 'Concealed storage', 'Carries the kitchen finish'],
    seoTitle: 'Dining Room Sideboard & Display Cabinetry, Philippines | Berco',
    seoDesc: 'Dining-room sideboards, bar and display cabinetry for Philippine homes — serving, storage and display planned for hosting. Design references from Berco.',
    keywords: ['dining room cabinetry Philippines', 'sideboard Philippines', 'bar cabinet Manila', 'display cabinet dining Philippines', 'Berco dining'],
    images: [
      { src: 'dining-room-cabinetry-tea-room-philippines.jpg', alt: 'Dining and tea room with warm fitted cabinetry and a garden view — Berco design reference', cap: 'Dining room · design reference' },
      { src: 'dining-display-cabinetry-table-philippines.jpg', alt: 'Dining area with a marble-topped table, upholstered chairs and floor-to-ceiling display and tall cabinetry — Berco design reference', cap: 'Dining & display wall' },
      { src: 'dining-open-plan-wine-display-philippines.jpg', alt: 'Open-plan dining with a table, tall cabinetry and a lit wine-display wall beside the kitchen — Berco design reference', cap: 'Dining & wine display', wide: true },
      { src: 'open-plan-living-dining-lounge-philippines.jpg', alt: 'Open-plan living and dining with a lounge, a dining table and a kitchen with display cabinetry beyond — Berco design reference', cap: 'Living, dining & kitchen' },
      { src: 'open-plan-living-dining-warm-philippines.jpg', alt: 'Warm open-plan living and dining with a media wall, an island with bar seating and a kitchen beyond — Berco design reference', cap: 'Open-plan living & dining', wide: true },
      { src: 'open-plan-dining-kitchen-warm-philippines.jpg', alt: 'Warm open-plan dining and kitchen with wood-lined display niches, a quartz breakfast bar and a garden view — Berco design reference', cap: 'Open to the kitchen', wide: true },
      { src: 'dining-sideboard-display-philippines.jpg', alt: 'Dining area with a sideboard and display cabinetry in green and wood — Berco design reference', cap: 'Sideboard & display', wide: true },
      { src: 'dining-bar-drinks-cabinet-philippines.jpg', alt: 'Dining area with a walnut bar and drinks cabinet beside a marble display — Berco design reference', cap: 'Bar & drinks' },
      { src: 'dining-wine-display-wall-philippines.jpg', alt: 'Dining room with an illuminated built-in wine-display wall — Berco design reference', cap: 'Display & wine' },
      { src: 'dining-room-cabinetry-philippines.jpg', alt: 'Dining room with display and wine-storage cabinetry — Berco design reference', cap: 'For hosting' },
      { src: 'grey-kitchen-dining-sideboard-philippines.jpg', alt: 'Grey semi-open kitchen with a dining table and an integrated sideboard — Berco design reference', cap: 'Kitchen-dining & sideboard', wide: true },
      { src: 'black-gold-kitchen-dining-philippines.jpg', alt: 'Matte-black and gold semi-open kitchen with a round dining table — Berco design reference', cap: 'Black & gold' },
      { src: 'walnut-dining-glass-display-cupboard-philippines.jpg', alt: 'Warm dining area with a tall walnut glass-display cupboard and a curved sofa — Berco design reference', cap: 'Walnut display cupboard' },
      { src: 'walnut-dining-sideboard-shelving-philippines.jpg', alt: 'Open-plan dining with a walnut sideboard and open display shelving — Berco design reference', cap: 'Walnut sideboard' },
      { src: 'walnut-dining-nook-display-philippines.jpg', alt: 'Warm walnut dining nook with a built-in display cabinet and appliance tower — Berco design reference', cap: 'Walnut dining nook' },
      { src: 'minimalist-dining-island-display-philippines.jpg', alt: 'Minimalist dining with a cream island and a glass-front display cabinet — Berco design reference', cap: 'Minimalist dining' },
      { src: 'modern-dining-fluted-marble-island-philippines.jpg', alt: 'Modern dining with fluted cabinetry and a marble-topped island — Berco design reference', cap: 'Fluted & marble' },
      { src: 'dining-stone-wall-marble-island-philippines.jpg', alt: 'Dining with a stone feature wall, display shelving and a marble island — Berco design reference', cap: 'Stone & marble' },
      { src: 'grey-terracotta-dining-island-philippines.jpg', alt: 'Grey dining run with a terracotta-and-marble island — Berco design reference', cap: 'Terracotta island' },
      { src: 'compact-kitchen-dining-table-philippines.jpg', alt: 'Compact kitchen with an integrated dining table and open-plan living beyond — Berco design reference', cap: 'Compact kitchen-dining' },
    ],
  },
  'interior-systems': {
    name: 'Interior Systems',
    hero: 'What makes a kitchen actually work.',
    lead: 'The fittings inside the cabinetry — pull-outs, organisers and the workstation sink — that make everyday storage effortless.',
    body: 'Good cabinetry is decided by what goes inside it. We plan it in the same function groups our catalogue does — drawer organisation, corner and tall storage, and sinks and taps — worked out around how you actually cook and store. Soft-close and push-to-open throughout, with named premium hardware from Kesseböhmer (Germany) and Peka (Switzerland). The flagship is a multifunction workstation sink that doubles as a second prep zone. Fitted to the cabinet, not added on.',
    types: [
      { name: 'Drawer Organisation', line: 'Base pull-outs, plate and cutlery baskets, in-drawer inserts.' },
      { name: 'Corner & Tall Storage', line: 'Larder pull-outs, lift systems and rotating corner units.' },
      { name: 'Sinks & Taps', line: 'The multifunction workstation sink, faucets and fittings.' },
    ],
    features: ['Drawer organisation & pull-outs', 'Corner & tall-unit access', 'Soft-close & push-to-open', 'Kesseböhmer · Germany · Peka · Switzerland'],
    seoTitle: 'Kitchen Interior Systems & Storage Fittings, Philippines | Berco',
    seoDesc: 'Pull-out organisers, dish and cutlery storage, corner access and the workstation sink — the fittings that make Berco cabinetry work. Design references, Philippines.',
    keywords: ['kitchen storage systems Philippines', 'pull-out organiser Philippines', 'workstation sink Philippines', 'cabinet accessories Manila', 'Berco interior systems'],
    images: [
      { src: 'kitchen-workstation-sink-marble-island-philippines.jpg', alt: 'Multifunction workstation sink with a walnut board and colander set into a marble island — Berco design reference', cap: 'The workstation sink · design reference', wide: true },
      { src: 'interior-systems-white-dish-pullout-philippines.jpg', alt: 'White soft-close pull-out drawers fitted with a plate and dish organiser — Berco design reference', cap: 'Dish pull-out' },
      { src: 'interior-systems-cream-larder-pullout-philippines.jpg', alt: 'Full-height cream larder with backlit pull-out shelves beside a built-in oven — Berco design reference', cap: 'Cream larder' },
      { src: 'interior-systems-knife-utensil-rack-philippines.jpg', alt: 'Door-mounted knife and utensil rack inside a cabinet against a marble surround — Berco design reference', cap: 'Utensil rack' },
      { src: 'interior-systems-drawer-system-detail-philippines.jpg', alt: 'Studio view of a fully fitted drawer system with organisers and dividers — Berco design reference', cap: 'Fitted drawer system' },
      { src: 'interior-systems-brass-drawer-organiser-philippines.jpg', alt: 'Deep drawers fitted with organisers and brass-topped bottles under a wood worktop — Berco design reference', cap: 'Fitted deep drawers' },
      { src: 'interior-systems-tall-pantry-pullout-philippines.jpg', alt: 'Tall slimline pantry pull-out stocked with jars and bottles — Berco design reference', cap: 'Tall pantry pull-out' },
      { src: 'interior-systems-bottle-drawer-storage-philippines.jpg', alt: 'Deep drawer fitted for bottle and pantry storage with timber dividers — Berco design reference', cap: 'Bottle storage' },
      { src: 'interior-systems-canister-drawer-philippines.jpg', alt: 'Drawer fitted with sealed canisters for grains and staples — Berco design reference', cap: 'Canister drawer' },
      { src: 'interior-systems-tall-pantry-luxe-philippines.jpg', alt: 'Full-height pantry pull-out in a dark luxe kitchen beside a freestanding tub — Berco design reference', cap: 'Luxe pantry pull-out' },
      { src: 'interior-systems-roller-shutter-garage-philippines.jpg', alt: 'Roller-shutter appliance garage keeping the worktop clear in a warm kitchen — Berco design reference', cap: 'Appliance garage' },
      { src: 'interior-systems-dish-cutlery-pullout-philippines.jpg', alt: 'Pull-out drawers with a fitted dish rack, cutlery-tray inserts and cup and jar organisers — Berco design reference', cap: 'Dish & cutlery pull-outs' },
      { src: 'interior-systems-jar-organiser-pullout-philippines.jpg', alt: 'Pull-out storage with a tiered spice and jar organiser and a plate rack — Berco design reference', cap: 'Spice & jar organiser' },
      { src: 'interior-systems-terracotta-pullout-storage-philippines.jpg', alt: 'Warm terracotta pull-out drawers with a fitted dish rack and cup holders — Berco design reference', cap: 'Fitted, front to back' },
      { src: 'interior-systems-worktop-integration-philippines.jpg', alt: 'Worktop with an integrated workstation sink and pull-out drawers organised with dishes and utensils beside an induction hob — Berco design reference', cap: 'Worktop & beyond', wide: true },
      { src: 'interior-systems-corner-pullout-philippines.jpg', alt: 'Corner cabinet pull-out shelving that brings pots and cookware out of the dead corner — Berco design reference', cap: 'Corner solutions' },
      { src: 'interior-systems-drawer-organisation-philippines.jpg', alt: 'Base-cabinet pull-out drawers with fitted plate, cutlery and jar organisers — Berco design reference', cap: 'Drawer organisation' },
      { src: 'interior-systems-larder-tall-storage-philippines.jpg', alt: 'Tall larder pull-out with full-extension tiers of pantry storage beside a built-in oven — Berco design reference', cap: 'Larders & tall storage' },
      { src: 'interior-systems-wall-lift-system-philippines.jpg', alt: 'Wall-cabinet pull-down lift system that brings upper-shelf storage down to reach — Berco design reference', cap: 'Wall & lift systems' },
      { src: 'interior-systems-workstation-sink-range-philippines.jpg', alt: 'Single-bowl workstation sink with a pull-out faucet set into a quartz worktop against a marble backsplash — Berco design reference', cap: 'The sink range', wide: true },
    ],
    catalogue: {
      title: 'The full Interior Systems range',
      intro: 'Every fitting, organised by function — drawer organisation, larders and tall storage, wall and lift systems, corner solutions, waste and rice, worktop integration, and sinks and taps. Codes, sizes and cabinet fits included.',
      pdf: '/berco-interior-systems-catalogue.pdf',
      pdfLabel: 'Download the Interior Systems catalogue (PDF)',
      pageDir: '/img/catalogue/interior-systems',
      pages: 32,
    },
  },
}
